spring.application.name=agencia-viagens

# Configurações Explícitas do Banco de Dados (Fallback e Produção)
spring.datasource.url=jdbc:postgresql://localhost:54328/destinos_db
spring.datasource.username=postgres
spring.datasource.password=devweb
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Manutenção do Schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true